### ISSUE TITLE
Aggregate and augment data from Influx DB into SQL DB

### ISSUE THREAD

**Issue by yohny** [ERNICommunity/hh-dust-be-enhancementservice#1]
Data from sensors are stored in Influx DB. We need to get them into SQL database (aggregated a bit, as Influx granularity is too much, we are fine with hourly averages).
After that we need to enhance the data with additional properties (wind speed, wind direction, atmospheric pressure).
Linking main repo issues here:
- ERNICommunity/dust-measurement-network/issues/32
- ERNICommunity/dust-measurement-network/issues/2

**Comment by yohny** [comment]
[Openwether API](https://openweathermap.org/history) we wanted to use is availabble only with subscription that starts at $150/month, so if we want to do this we need a different source.
Some alternatives to explore:
https://darksky.net/dev/docs/time-machine#time-machine-request
http://apidev.accuweather.com/developers/
https://developer.worldweatheronline.com/api/docs/historical-weather-api.aspx
https://api.met.no/

**Comment by wtvisser** [comment]
@dniklaus can you please clarify if we have budget to purchase the OpenWeather API subscription?

**Comment by dniklaus** [comment]
@wtvisser and @yohny: unfortunately we have no budget for the [Openwether API](https://openweathermap.org/history) subscription up to now. 
Would one of the alternatives mentioned above be working for us?

**Comment by yohny** [comment]
the alternatives above are just a result of a quick web search, they need to be analyzed deeper to see if they can provide us historical weather information based on lat/lon coordinates
I'll try to get a closer look in upcoming days

**Comment by dorny** [comment]
worldweatheronline looks good. They have 250 requests / day for free. This should be enough for us.

**Comment by yohny** [comment]
closing in favour of ERNICommunity/hh-dust-fe-be#5
