### ISSUE TITLE
Shared data model

### ISSUE THREAD

**Issue by dorny** [ERNICommunity/hh-dust-be-enhancementservice#2]
Our current architecture means both enhancement service and web ui backend uses same SQL database.
However those components are in separate repos. How about moving everything into dust-measurement-network repo and have a shared data model lib?

**Comment by dniklaus** [comment]
In order to avoid issues like this I initially suggested to do everything in one repository.

**Comment by dorny** [comment]
I know...  still this part and also Web UI ended in seprate repos. So @alain4erni , @yohny can we move your code into https://github.com/ERNICommunity/dust-measurement-network ?

**Comment by yohny** [comment]
I plan to have EF model separated into its own project so it can be reused by all backed projects (as no other than backend projects need it), I hopefully find time to do it until the end of the week. Afterwards I will move the enhancement service into https://github.com/ERNICommunity/hh-dust-fe-be repo

**Comment by yohny** [comment]
resolved, we have shared model project and dummy (for now) console app in https://github.com/ERNICommunity/hh-dust-fe-be repo
